<?php
// $Id$
/**
 * @file security_violations.module
 * This is just to demonstrate BAD security practices.
 */


/**
 * Implementation of hook_init().
 * Warn people they really shouldn't be running this module.
 */
function security_violations_init() {
  drupal_set_message(t('This site is running the "Security Violations" module which should <strong>never</strong> be enabled on a <em>public</em> website.  If this is a public website, you should immediately <a href="!uri">disable it</a>', array('!uri' => url('admin/build/modules'))));
}

/**
 * Implementation of hook_menu().
 */
function security_violations_menu() {
  // A general form
  $items['security_violations'] = array(
    'title' => 'Security Violations',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('security_violations_basic'),
    'access callback' => TRUE,
  );

  // access to /unprotected_delete/nid will result in the deletion of the node
  // if the user has 'delete any page content' permission and the nid number
  // provided exists and is of type 'page'.
  $items['unprotected_delete'] = array(
    'page callback' => 'security_violations_unprotected_delete',
    'access arguments' => array('delete any page content'),
  );
  return $items;
}

/**
 * Present a form with some clear security issues.
 */
function security_violations_basic(&$form_state) {
  if (isset($_SESSION['anytext'])) {
    $form['markup1'] = array(
      '#type' => 'markup',
      '#value' => '<div>You entered: ' .   $_SESSION['anytext'] . check_plain($_SESSION['anytext']) . '</div>',
    );
  }
  if (isset($_SESSION['uid'])) {
    // This query is dangerous and horribly insecure.
    $username = db_result(db_query("SELECT name FROM {users} WHERE uid=" . $_SESSION['uid']));

    // This query shows correct usage of db_query().
    $correct_username = db_result(db_query("SELECT name FROM {users} WHERE uid=%d", $_SESSION['uid']));
    $form['markup2'] = array(
      '#type' => 'markup',
      '#value' => '<div>' . t('The username for uid %uid is %name (you may have wanted %correct_username instead)', array('%name' => $username, '%correct_username' => $correct_username, '%uid' => $_SESSION['uid'])) . '</div>',
    );
  }
  // Try entering <script>alert("your site will be hacked");</script>
  $form['anytext'] = array(
    '#type' => 'textarea',
    '#title' => t('Enter any text you want to display here'),
    '#default_value' => !empty($_SESSION['anytext']) ? $_SESSION['anytext'] : '<script>alert("your site will be hacked");</script>',
  );

  // Try entering
  // 11111 OR pass=md5("nothing")
  // and get the first user with a password set to "nothing".
  $form['uid'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter your uid here and I will give you your username'),
    '#description' => t('Or you might try the insidious "11111 OR pass=md5("nothing")"'),
    '#default_value' => !empty($_SESSION['uid']) ? $_SESSION['uid'] : '',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

/**
 * Submit handler for security_violations_basic().
 */
function security_violations_basic_submit($form, &$form_state) {
  $_SESSION['anytext'] = $form_state['values']['anytext'];
  $_SESSION['uid'] = $form_state['values']['uid'];
}

/**
 * Delete a node if it exists and is a page.
 *
 * @param $nid
 *   The nid to be deleted.
 */
function security_violations_unprotected_delete($nid = 0) {
  $node = node_load($nid);
  if (!empty($node) && $node->type == 'page') {
    node_delete($nid);
    return(t('Deleted node %title', array('%title' => $node->title)));
  }
  else {
    return(t('No page node with nid=%nid was found', array('%nid' => $nid)));
  }
}